import { Component, OnInit } from '@angular/core';
import {Set} from './set';

@Component({
  selector: 'app-mu-shop',
  templateUrl: './mu-shop.component.html',
  styleUrls: ['./mu-shop.component.scss']
})
export class MuShopComponent implements OnInit {
  
  sets: Set[] = [
    {
      name:'Leather',
      pjclass:['Blade Knight','Magic Gladiator','Dark Lord'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/Leather.png',
    },
    {
      name:'Bronze',
      pjclass:['Blade Knight','Magic Gladiator','Dark Lord'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/bronze.png',
    },
    {
      name:'Brass',
      pjclass:['Blade Knight','Magic Gladiator'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/brass.png',
    },
    {
      name:'Scale',
      pjclass:['Blade Knight','Magic Gladiator','Dark Lord'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/scale.png',
    },
    {
      name:'Plate',
      pjclass:['Blade Knight','Magic Gladiator'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/plate.png',
    },
    {
      name:'Dragon',
      pjclass:['Blade Knight','Magic Gladiator'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/dragon.png',
    },
    {
      name:'Black Dragon',
      pjclass:['Blade Knight'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/blackdragon.png',
    },
    {
      name:'Dark Phoenix',
      pjclass:['Blade Knight'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/phoenix.png',
    },
    {
      name:'Great Dragon',
      pjclass:['Blade Knight'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/greatdragon.png',
    },
    {
      name:'Pad',
      pjclass:['Soul Master','Magic Gladiator'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/pad.png',
    },
    {
      name:'Bone',
      pjclass:['Soul Master','Magic Gladiator'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/bone.png',
    },
    {
      name:'Sphinx',
      pjclass:['Soul Master','Magic Gladiator'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/sphinx.png',
    },
    {
      name:'Legendary',
      pjclass:['Soul Master','Magic Gladiator'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/legendary.png',
    },
    {
      name:'Grand Soul',
      pjclass:['Soul Master'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/grandsoul.png',
    },
    {
      name:'Dark Soul',
      pjclass:['Soul Master'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/darksoul.png',
    },
    {
      name:'Vine',
      pjclass:['Muse Elf'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/vine.png',
    },
    {
      name:'Silk',
      pjclass:['Muse Elf'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/silk.png',
    },
    {
      name:'Wind',
      pjclass:['Muse Elf'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/wind.png',
    },
    {
      name:'Spirit',
      pjclass:['Muse Elf'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/spirit.png',
    },
    {
      name:'Guardian',
      pjclass:['Muse Elf'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/guardian.png',
    },
    {
      name:'Divine',
      pjclass:['Muse Elf'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/divine.png',
    },
    {
      name:'Red Spirit',
      pjclass:['Muse Elf'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/redspirit.png',
    },
    {
      name:'Light Plate',
      pjclass:['Dark Lord'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/lightplate.png',
    },
    {
      name:'Adamantine',
      pjclass:['Dark Lord'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/adamantine.png',
    },
    {
      name:'Dark Stee',
      pjclass:['Dark Lord'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/darksteel.png',
    },
    {
      name:'Dark Master',
      pjclass:['Dark Lord'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/darkmaster.png',
    },
    {
      name:'Storm Crow',
      pjclass:['Magic Gladiator'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/stormcrow.png',
    },
    {
      name:'Thunder Hawk',
      pjclass:['Magic Gladiator'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/thunder.png',
    },
    {
      name:'Hurricane',
      pjclass:['Magic Gladiator'],
      stock:10,
      quantity:0,
      precio:15,
      image:'assets/images/hurricane.png',
    },

  ];

  constructor() { }

  ngOnInit(): void {
  }

}
